import './globals.css'
import Footer from '@/components/ui/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-gray-900 to-gray-700">
        <header title='Bilderwelt' />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
